### ISSUE TITLE
Can't resolve 'dns'

### ISSUE THREAD

**Issue by okaysuper** [vercel/fetch#53]
Hello,

I'm trying to use @vercel/fetch in nextjs on the serverside
Whatever I try I always have the same error:

./node_modules/@zeit/dns-cached-resolve/lib/dns-resolve.js:6:0
Module not found: Can't resolve 'dns'

Am I doing something wrong?

Thanks for your help.

**Comment by nsmith7989** [comment]
@okaysuper I had the same problem trying to use this in nextjs. I think the problem is that `dns` is built into node, but isn't available in the browser. You need to make sure you're using this server side only. 

I have a file that is both server and client side so my solution is something like:

```js
function getFetch() {
  if (typeof window === 'undefined') {
    const createFetch = require('@vercel/fetch');
    return createFetch();
  }
  return window.fetch;
}
```

Alternatively if you're in nextjs and doing something in `getStaticProps` or `getServerSideProps` if you only use this package there nextjs will take care of not including this in the client bundle and causing errors.

**Comment by Ethan-Arrowood** [comment]
Thank you for the report. We are archiving this project; you can read more details here: https://github.com/vercel/fetch/issues/83
